{
	"schema_version": "1.6.0",
	"id": "MAL-2025-957",
	"modified": "2025-02-03T17:07:41Z",
	"published": "2025-02-03T17:07:41Z",
	"summary": "Malicious code in pyethereum2345 (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pyethereum2345",
				"purl": "pkg:pypi/pyethereum2345"
			},
			"versions": [
				"0.10"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pyethereum2345/MAL-2025-957.json"
			}
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2025-00498",
				"import_time": "2025-02-03T18:38:07.90133484Z",
				"modified_time": "2025-02-03T17:07:41Z",
				"sha256": "0b41e53ff77d6b30f53abf749a6940685d765f146401896764f9cd6219516087",
				"source": "reversing-labs",
				"versions": [
					"0.10"
				]
			}
		]
	}
}
