{
	"schema_version": "1.6.0",
	"id": "PYSEC-2022-43152",
	"modified": "2024-11-21T14:23:00.061403Z",
	"published": "2022-09-01T18:15:00Z",
	"details": "A flaw was found in the python-scciclient when making an HTTPS connection to a server where the server's certificate would not be verified. This issue opens up the connection to possible Man-in-the-middle (MITM) attacks.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "python-scciclient",
				"purl": "pkg:pypi/python-scciclient"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"0.0.1",
				"0.1.0",
				"0.10.0",
				"0.10.1",
				"0.10.2",
				"0.11.0.dev1",
				"0.11.1",
				"0.11.2",
				"0.11.3",
				"0.11.4",
				"0.12.0",
				"0.12.1",
				"0.12.2",
				"0.12.3",
				"0.13.0",
				"0.14.0",
				"0.15.0",
				"0.16.0",
				"0.2.0",
				"0.3.0",
				"0.3.1",
				"0.4.0",
				"0.5.0",
				"0.6.0",
				"0.6.1",
				"0.6.2",
				"0.7.0",
				"0.7.1",
				"0.7.2",
				"0.7.3",
				"0.7.4",
				"0.8.0",
				"0.8.1",
				"0.8.2",
				"0.8.2.dev1",
				"0.8.3",
				"0.8.3.dev1",
				"0.9.0",
				"0.9.1",
				"0.9.2",
				"0.9.2.dev1",
				"0.9.2.dev3",
				"0.9.3",
				"0.9.4",
				"0.9.5"
			],
			"database_specific": {
				"source": "https://github.com/pypa/advisory-database/blob/main/vulns/python-scciclient/PYSEC-2022-43152.yaml"
			}
		}
	],
	"references": [
		{
			"type": "WEB",
			"url": "https://opendev.org/x/python-scciclient/commit/274dca0344b65b4ac113d3271d21c17e970a636c"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2022/11/msg00006.html"
		}
	]
}
