{
	"schema_version": "1.6.0",
	"id": "MAL-2024-4937",
	"modified": "2024-10-24T01:01:58Z",
	"published": "2024-06-25T13:33:47Z",
	"aliases": [
		"SNYK-PYTHON-COLORAMXA-6513369"
	],
	"summary": "Malicious code in coloramxa (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "coloramxa",
				"purl": "pkg:pypi/coloramxa"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/coloramxa/MAL-2024-4937.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-COLORAMXA-6513369"
		},
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-03717",
				"import_time": "2024-06-28T02:48:35.541285699Z",
				"modified_time": "2024-06-25T13:33:47Z",
				"sha256": "c1e3a8c4c6874d29651915550693d95fbc17a5f11b6ad7fb95d7d67c5f792d78",
				"source": "reversing-labs",
				"versions": [
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-08008",
				"import_time": "2024-10-24T00:58:57.810386548Z",
				"modified_time": "2024-10-16T14:38:21Z",
				"sha256": "3ec0f1587dfcbf2bc3b3354ae038991f63c00c172b746379644aa9a579ab7d3e",
				"source": "reversing-labs"
			}
		]
	}
}
