{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5917",
	"modified": "2024-10-24T01:01:59Z",
	"published": "2024-06-25T13:41:50Z",
	"aliases": [
		"SNYK-PYTHON-REQUIEREMENT-6513605"
	],
	"summary": "Malicious code in requierement (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "requierement",
				"purl": "pkg:pypi/requierement"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/requierement/MAL-2024-5917.json"
			}
		}
	],
	"references": [
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-REQUIEREMENT-6513605"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04718",
				"import_time": "2024-06-28T02:50:33.689246697Z",
				"modified_time": "2024-06-25T13:41:50Z",
				"sha256": "28bfe7d0fb954a3951f9b2e1ec89c95316f01c5ca66cd03a0c3ee7811728b649",
				"source": "reversing-labs",
				"versions": [
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-09177",
				"import_time": "2024-10-24T01:00:05.420095759Z",
				"modified_time": "2024-10-16T14:50:26Z",
				"sha256": "bed0f36168c3e1c93603f818652d380d47f2aa66e3d6da975df6c3a486e2b74d",
				"source": "reversing-labs"
			}
		]
	}
}
