{
	"schema_version": "1.6.0",
	"id": "MAL-2024-6058",
	"modified": "2024-06-25T13:42:58Z",
	"published": "2024-06-25T13:42:58Z",
	"summary": "Malicious code in synapse-x (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "synapse-x",
				"purl": "pkg:pypi/synapse-x"
			},
			"versions": [
				"0.1.3"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/synapse-x/MAL-2024-6058.json"
			}
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04861",
				"import_time": "2024-06-28T02:50:51.175182789Z",
				"modified_time": "2024-06-25T13:42:58Z",
				"sha256": "5e8efd01428730367cbd6be2021e95d008860218c61e734db07b0f0f9cf21214",
				"source": "reversing-labs",
				"versions": [
					"0.1.3"
				]
			}
		]
	}
}
