{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5009",
	"modified": "2024-10-24T01:01:58Z",
	"published": "2024-06-25T13:34:21Z",
	"aliases": [
		"SNYK-PYTHON-CSTMOTKINTER-6513557"
	],
	"summary": "Malicious code in cstmotkinter (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "cstmotkinter",
				"purl": "pkg:pypi/cstmotkinter"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/cstmotkinter/MAL-2024-5009.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-CSTMOTKINTER-6513557"
		},
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-03789",
				"import_time": "2024-06-28T02:48:43.697060792Z",
				"modified_time": "2024-06-25T13:34:21Z",
				"sha256": "e4f86c12d6cdc3df0619cf665e7c8a6c2ee6b46390233e10b886ce09b437c066",
				"source": "reversing-labs",
				"versions": [
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-08084",
				"import_time": "2024-10-24T00:59:02.932881294Z",
				"modified_time": "2024-10-16T14:39:10Z",
				"sha256": "daee9e467c658c22bf48873a8f84c0739180385b12235ab5d4a9f0c2330192d0",
				"source": "reversing-labs"
			}
		]
	}
}
