{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5584",
	"modified": "2024-10-24T01:01:59Z",
	"published": "2024-06-25T13:39:00Z",
	"aliases": [
		"SNYK-PYTHON-PYCIRD-6513353"
	],
	"summary": "Malicious code in py-cird (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "py-cird",
				"purl": "pkg:pypi/py-cird"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/py-cird/MAL-2024-5584.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCIRD-6513353"
		},
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04366",
				"import_time": "2024-06-28T02:49:51.786112173Z",
				"modified_time": "2024-06-25T13:39:00Z",
				"sha256": "028a40b2d97abfe1fde451ae3fef789db6bc27926f812bafc5393b6c98b27c50",
				"source": "reversing-labs",
				"versions": [
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-08799",
				"import_time": "2024-10-24T00:59:42.403107408Z",
				"modified_time": "2024-10-16T14:46:35Z",
				"sha256": "9b7c20826b4d5ce86be58e02508f6abd4012ae5679771d8d1b3706a0a77e3341",
				"source": "reversing-labs"
			}
		]
	}
}
