{
	"schema_version": "1.6.0",
	"id": "MAL-2024-4936",
	"modified": "2024-10-24T01:01:58Z",
	"published": "2024-06-25T13:33:46Z",
	"aliases": [
		"SNYK-PYTHON-COLORAMWS-6513693"
	],
	"summary": "Malicious code in coloramws (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "coloramws",
				"purl": "pkg:pypi/coloramws"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/coloramws/MAL-2024-4936.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-COLORAMWS-6513693"
		},
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-03716",
				"import_time": "2024-06-28T02:48:35.432590284Z",
				"modified_time": "2024-06-25T13:33:46Z",
				"sha256": "ef0916d90d4fee23661994b87d612513e0f1ecec9cd6381187e744050af836d9",
				"source": "reversing-labs",
				"versions": [
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-08007",
				"import_time": "2024-10-24T00:58:57.748352763Z",
				"modified_time": "2024-10-16T14:38:21Z",
				"sha256": "b0198e54938521d642a4c5db65ca7bad428ad9637b3b36fad47d181de5b37484",
				"source": "reversing-labs"
			}
		]
	}
}
