{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5539",
	"modified": "2024-10-24T01:01:59Z",
	"published": "2024-06-25T13:38:38Z",
	"aliases": [
		"SNYK-PYTHON-PIPSQLIEXT-5591173"
	],
	"summary": "Malicious code in pipsqliext (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pipsqliext",
				"purl": "pkg:pypi/pipsqliext"
			},
			"versions": [
				"1.1.0",
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pipsqliext/MAL-2024-5539.json"
			}
		}
	],
	"references": [
		{
			"type": "ARTICLE",
			"url": "https://blog.phylum.io/respawning-malware-persists-on-pypi/"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-PIPSQLIEXT-5591173"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04321",
				"import_time": "2024-06-28T02:49:46.571179024Z",
				"modified_time": "2024-06-25T13:38:38Z",
				"sha256": "0f9144bce834a8739c4accd2265de6770d787b7d79d37e241f2041cdbf782fe5",
				"source": "reversing-labs",
				"versions": [
					"1.1.0",
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-08749",
				"import_time": "2024-10-24T00:59:39.26713964Z",
				"modified_time": "2024-10-16T14:46:04Z",
				"sha256": "70f7b40d6abc8341e627b9c9d525f48c1f35cc3c3f42eda45d44b54bb953823c",
				"source": "reversing-labs"
			}
		]
	}
}
