{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5622",
	"modified": "2024-10-24T01:01:59Z",
	"published": "2024-06-25T13:39:18Z",
	"aliases": [
		"SNYK-PYTHON-PYCOWRD-6513663"
	],
	"summary": "Malicious code in py-cowrd (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "py-cowrd",
				"purl": "pkg:pypi/py-cowrd"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/py-cowrd/MAL-2024-5622.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYCOWRD-6513663"
		},
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04404",
				"import_time": "2024-06-28T02:49:56.321526825Z",
				"modified_time": "2024-06-25T13:39:18Z",
				"sha256": "0ca0de2d13f4f5750a9f8e90fbcf1f6312057d490ce94ce0ebd8c764aec9e1cc",
				"source": "reversing-labs",
				"versions": [
					"1.0.0"
				]
			},
			{
				"id": "RLUA-2024-08837",
				"import_time": "2024-10-24T00:59:45.155155174Z",
				"modified_time": "2024-10-16T14:46:58Z",
				"sha256": "bd96cdbc4d48942ebc7899b5230ae604ebf4321edc8055a8d01c92f2c6c2b138",
				"source": "reversing-labs"
			}
		]
	}
}
