{
	"schema_version": "1.6.0",
	"id": "MAL-2024-5826",
	"modified": "2024-06-28T03:15:11.801127Z",
	"published": "2024-06-25T13:41:05Z",
	"aliases": [
		"SNYK-PYTHON-PYTHONSQLITEDBEXTV1-5591190",
		"SNYK-PYTHON-PYTHONSQLITEDBEXTV1-5932346"
	],
	"summary": "Malicious code in pythonsqlitedbextv1 (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pythonsqlitedbextv1",
				"purl": "pkg:pypi/pythonsqlitedbextv1"
			},
			"versions": [
				"1.1.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pythonsqlitedbextv1/MAL-2024-5826.json"
			}
		}
	],
	"references": [
		{
			"type": "ARTICLE",
			"url": "https://blog.phylum.io/respawning-malware-persists-on-pypi/"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYTHONSQLITEDBEXTV1-5932346"
		},
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/the-evolutionary-tale-of-a-persistent-python-threat-d19196d4ed15"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-PYTHONSQLITEDBEXTV1-5591190"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-04624",
				"import_time": "2024-06-28T02:50:22.141041284Z",
				"modified_time": "2024-06-25T13:41:05Z",
				"sha256": "c797178a2df068638f80420e59c32194314bc1bdbcddf16b22c9499c993bf454",
				"source": "reversing-labs",
				"versions": [
					"1.1.0"
				]
			}
		]
	}
}
