{
	"schema_version": "1.6.0",
	"id": "MAL-2024-10111",
	"modified": "2024-10-16T14:47:10Z",
	"published": "2024-10-16T14:47:10Z",
	"summary": "Malicious code in pyadd (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "pyadd",
				"purl": "pkg:pypi/pyadd"
			},
			"versions": [
				"0.1.0",
				"0.1.1",
				"0.1.2",
				"0.1.3",
				"0.1.4"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pyadd/MAL-2024-10111.json"
			}
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-08857",
				"import_time": "2024-10-24T00:57:05.165231074Z",
				"modified_time": "2024-10-16T14:47:10Z",
				"sha256": "9cb98ba09efcb0966c2a890f45003b093ff42dda2b702d0128002938d8573871",
				"source": "reversing-labs",
				"versions": [
					"0.1.0",
					"0.1.1",
					"0.1.2",
					"0.1.3",
					"0.1.4"
				]
			}
		]
	}
}
