{
	"schema_version": "1.6.0",
	"id": "MAL-2024-4866",
	"modified": "2024-06-28T03:14:48.444776Z",
	"published": "2024-06-25T13:33:12Z",
	"aliases": [
		"SNYK-PYTHON-CAPMONSTERCLOUDCLINET-6513709"
	],
	"summary": "Malicious code in capmonstercloudclinet (PyPI)",
	"details": "\n---\n_-= Per source details. Do not edit below this line.=-_\n",
	"affected": [
		{
			"package": {
				"ecosystem": "PyPI",
				"name": "capmonstercloudclinet",
				"purl": "pkg:pypi/capmonstercloudclinet"
			},
			"versions": [
				"1.0.0"
			],
			"database_specific": {
				"source": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/capmonstercloudclinet/MAL-2024-4866.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-CAPMONSTERCLOUDCLINET-6513709"
		},
		{
			"type": "ARTICLE",
			"url": "https://medium.com/checkmarx-security/pypi-is-under-attack-project-creation-and-user-registration-suspended-heres-the-details-c3b6291d4579"
		}
	],
	"credits": [
		{
			"name": "ReversingLabs",
			"contact": [
				"https://www.reversinglabs.com"
			],
			"type": "FINDER"
		}
	],
	"database_specific": {
		"malicious-packages-origins": [
			{
				"id": "RLMA-2024-03646",
				"import_time": "2024-06-28T02:48:27.246881892Z",
				"modified_time": "2024-06-25T13:33:12Z",
				"sha256": "dfc5bacaa23f668f2d7737658e1459b1cf1b7eda0bdadff22cf49392ed03912c",
				"source": "reversing-labs",
				"versions": [
					"1.0.0"
				]
			}
		]
	}
}
